Repository ECSIM/opem, pull requests merged in 2021-03, with the labels that each got.

#149 Chakraborty Model
  .travis/test.sh
  CHANGELOG.md
  Documents/Chakraborty.ipynb
  Documents/Chakraborty/Chakraborty_Test.csv
  Documents/Chakraborty/Chakraborty_Test.html
  Documents/Chakraborty/Chakraborty_Test.opem
  Documents/README.md
  Documents/images/Chakraborty-Diagram.jpg
  MATLAB/Chakraborty.m
  README.md
  opem/Dynamic/Chakraborty.py
  opem/Params.py
  opem/Test/test_Chakraborty.py
  opem/__init__.py
  opem/__main__.py
Labels: enhancement, new model

#148 Test system
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .travis.yml
  .travis/install.sh
  .travis/test.sh
  CHANGELOG.md
  README.md
  appveyor.yml
  codecov.yml
  dev-requirements.txt
  otherfile/requirements-splitter.py
  pytest.ini
Labels: test

#151 Improve HTML Report
  CHANGELOG.md
  opem/Functions.py
  opem/Params.py
Labels: bug
